logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: jwtsecretkey
  
server:
  port: 8888
  
spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
      username: {사용자명}
      password: {비밀번호}
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 176913025957-fr37dul2musncu6sqmo2j8m1h7ag6nv6.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: 5IND8_PuX8qLA_IoSj5d
            client-secret: hKxJgZsfqR
            redirect-uri: http://localhost:8888/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: 6aa864359ded828950f008c46acd8740
            redirect-uri: http://localhost:8888/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id