# 서버 포트 설정
server:
  port: 8888

# database 연동 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/project?characterEncoding=UTF-8&serverTimezone=UTC
    username: jjun
    password: 1234
  thymeleaf:
    cache: false

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://db.jjuns-c.com:3306/dbjjundesign?characterEncoding=UTF-8&serverTimezone=UTC
#    username: jjundesign
#    password: jjundesign2023
#  thymeleaf:
#    cache: false
    
  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update